### ISSUE TITLE
missing components_definition.ipynb ? 

### ISSUE THREAD

**Issue by david-dirring** [hernanescu/vertex-pipelines-kfp-chicago#1]
Great repo, thanks for the details on how you leveraged vertex in this example.
I was not able to find components_definition.ipynb file?  can you take a look. thanks!

**Comment by hernanescu** [comment]
Hi, you're welcome! The notebook is inside the components folder itself =)
Have a great day, let me know if that was useful!

**Comment by david-dirring** [comment]
oh man, sorry, thanks!
